development:
  password: ""
  theme_id: ""
  store: mudzhiri.myshopify.com
  ignore_files:
    - config/settings_data.json

production:
  password: ""
  theme_id: ""
  store: mudzhiri.myshopify.com
  ignore_files:
    - config/settings_data.json

